[package]
name = "lens-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "lens"
path = "src/main.rs"

[dependencies]
lens-core = { path = "../lens-core" }
lens-disk = { path = "../lens-disk" }
lens-abi = { path = "../lens-abi" }
lens-log = { path = "../lens-log" }
lens-test = { path = "../lens-test" }
lens-trace = { path = "../lens-trace" }
lens-sys = { path = "../lens-sys" }
lens-build = { path = "../lens-build" }
lens-env = { path = "../lens-env" }
lens-net = { path = "../lens-net" }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
flate2 = { workspace = true }
